flaskProg/articles/routes.py
from flask import Blueprint, render_template, url_for, redirect, flash, request
from flaskProg.models import Article
from flaskProg.articles.forms import ArticleForm
from flaskProg import db

articles = Blueprint('articles', __name__)

@articles.route("/articles")
def viewArticles():
	articles = Article.query.all()
	return render_template('viewArticles.html', articles=articles)
	
@articles.route("/addArticle", methods=['GET','POST'])
def addArticle():
	form = ArticleForm()
	if form.validate_on_submit():
		article = Article(name=form.name.data, desc=form.desc.data, fruit=form.fruit.data, price=form.price.data, amountLiter=form.amountLiter.data)
		db.session.add(article)
		db.session.commit()
		flash('Neuer Artikel angelegt: %s' % form.name.data, 'success')
		return redirect(url_for("articles.viewArticles"))
	return render_template('addArticle.html', form=form)
	
@articles.route("/editArticle/<int:article_id>", methods=['GET','POST'])
def editArticle(article_id):
	article = Article.query.get_or_404(article_id)
	form = ArticleForm()
	if form.validate_on_submit():
		article.name = form.name.data
		article.desc = form.desc.data
		article.fruit = form.fruit.data
		article.price = form.price.data
		article.amountLiter = form.amountLiter.data
		db.session.commit()
		flash('Artikel bearbeitet: %s' % article.name, 'success')
		return redirect(url_for("articles.viewArticles"))
	elif request.method == 'GET':
		form.name.data = article.name
		form.desc.data = article.desc
		form.fruit.data = article.fruit
		form.price.data = article.price
		form.amountLiter.data = article.amountLiter
	return render_template('editArticle.html', form=form)
	
@articles.route("/deleteArticle/<int:article_id>", methods=['GET','POST'])
def deleteArticle(article_id):
	article = Article.query.get_or_404(article_id)
	db.session.delete(article)
	db.session.commit()
	flash('Artikel geloescht: %s' % article.name, 'success')
	return redirect(url_for("articles.viewArticles"))

flaskProg/boxes/routes.py
from flask import Blueprint, render_template, url_for, redirect, flash, request
from flaskProg.models import Box
from flaskProg.boxes.forms import BoxForm
from flaskProg import db

boxes = Blueprint('boxes', __name__)

@boxes.route("/boxes")
def viewBoxes():
	boxes = Box.query.all()
	return render_template('viewBoxes.html', boxes=boxes)
	
@boxes.route("/addBox", methods=['GET','POST'])
def addBox():
	form = BoxForm()
	if form.validate_on_submit():
		box = Box(number=form.number.data, content=form.content.data)
		db.session.add(box)
		db.session.commit()
		flash('Neue Kiste angelegt: %s' % form.number.data, 'success')
		return redirect(url_for("boxes.viewBoxes"))
	return render_template('addBox.html', form=form)
	
@boxes.route("/editBox/<int:box_id>", methods=['GET','POST'])
def editBox(box_id):
	box = Box.query.get_or_404(box_id)
	form = BoxForm()
	if form.validate_on_submit():
		box.number = form.number.data
		box.content = form.content.data
		db.session.commit()
		flash('Kiste bearbeitet: %s' % box.number, 'success')
		return redirect(url_for("boxes.viewBoxes"))
	elif request.method == 'GET':
		form.number.data = box.number
		form.content.data = box.content
	return render_template('editBox.html', form=form)
	
@boxes.route("/deleteBox/<int:box_id>", methods=['GET','POST'])
def deleteBox(box_id):
	box = Box.query.get_or_404(box_id)
	db.session.delete(box)
	db.session.commit()
	flash('Kiste geloescht: %s' % box.number, 'success')
	return redirect(url_for("boxes.viewBoxes"))

flaskProg/customers/routes.py
from flask import Blueprint, render_template, url_for, redirect, flash, request
from flaskProg.models import Customer, Fruit
from flaskProg.customers.forms import CustomerForm
from flaskProg import db

customers = Blueprint('customers', __name__)

@customers.route("/customers")
def viewCustomers():
	customers = Customer.query.all()
	fruits = Fruit.query.all()
	return render_template('viewCustomers.html', customers=customers, fruits=fruits)
	
@customers.route("/addCustomer", methods=['GET','POST'])
def addCustomer():
	form = CustomerForm()
	if form.validate_on_submit():
		customer = Customer(name=form.name.data, street=form.street.data, zipcode=form.zipcode.data, city=form.city.data, email=form.email.data, phone=form.phone.data, mobile=form.mobile.data)
		db.session.add(customer)
		db.session.commit()
		flash('Neuer Kunde angelegt: %s' % form.name.data, 'success')
		return redirect(url_for("customers.viewCustomers"))
	return render_template('addCustomer.html', form=form)
	
@customers.route("/editCustomer/<int:customer_id>", methods=['GET','POST'])
def editCustomer(customer_id):
	customer = Customer.query.get_or_404(customer_id)
	form = CustomerForm()
	form.validate_on_submit()
	if form.validate_on_submit():
		customer.name = form.name.data
		customer.street = form.street.data
		customer.zipcode = form.zipcode.data
		customer.city = form.city.data
		customer.email = form.email.data
		customer.phone = form.phone.data
		customer.mobile = form.mobile.data
		db.session.commit()
		flash('Kunde bearbeitet: %s' % customer.name, 'success')
		return redirect(url_for("customers.viewCustomers"))
	elif request.method == 'GET':
		form.name.data = customer.name
		form.street.data = customer.street
		form.zipcode.data = customer.zipcode
		form.city.data = customer.city
		form.email.data = customer.email
		form.phone.data = customer.phone
		form.mobile.data = customer.mobile
	return render_template('editCustomer.html', form=form)
	

@customers.route("/viewCustomer/<int:customer_id>", methods=['GET','POST'])
def viewCustomer(customer_id):
	customer = Customer.query.get_or_404(customer_id)
	fruits = Fruit.query.all()
	return render_template('viewCustomer.html', customer=customer, fruits=fruits)	

@customers.route("/deleteCustomer/<int:customer_id>", methods=['GET','POST'])
def deleteCustomer(customer_id):
	customer = Customer.query.get_or_404(customer_id)
	db.session.delete(customer)
	db.session.commit()
	flash('Kunde geloescht: %s' % customer.name, 'success')
	return redirect(url_for("customers.viewCustomers"))

flaskProg/deposits/routes.py
from flask import Blueprint, render_template, url_for, redirect, flash, request
from flaskProg.models import Deposit, DepositItem, Fruit, Box, Customer
from flaskProg.deposits.forms import EmptyDepositItemForm, DepositItemForm, DepositForm, FruitListForm
from flaskProg import db
from datetime import datetime

deposits = Blueprint('deposits', __name__)

@deposits.route("/deposits")
def viewDeposits():
	deposits = Deposit.query.all()
	fruits = Fruit.query.all()
	return render_template('viewDeposits.html', deposits=deposits, fruits=fruits)

@deposits.route("/addDeposit", methods=['GET','POST'])
@deposits.route("/addDeposit/<int:customer_id>", methods=['GET','POST'])
def addDeposit(customer_id=-1):
	form = DepositForm()
	form.validate_on_submit()
	if form.validate_on_submit():
		deposit = Deposit(date=form.date.data, customer=form.customer.data)
		db.session.add(deposit)
		for entry in form.depositItems.entries:
			if entry.amount.data > 0:
				box = Box.query.get_or_404(entry.box.data)
				depositItem = DepositItem(box=box, amount=entry.amount.data, deposit=deposit, amountLiter=entry.amountLiter.data, amountEuro=entry.amountEuro.data)
				db.session.add(depositItem)
		for entry in form.emptyDepositItems.entries:
			if entry.amount.data > 0:
				box = Box(number=entry.boxNumber.data, content=entry.boxContent.data)
				db.session.add(box)
				db.session.commit()
				depositItem = DepositItem(box=box, amount=entry.amount.data, deposit=deposit, amountLiter=entry.amountLiter.data, amountEuro=entry.amountEuro.data)
				db.session.add(depositItem)
		db.session.commit()
		flash('Neue Gutschrift angelegt','success')
		return redirect(url_for("deposits.viewDeposits"))
	if len(form.depositItems) == 0:
		boxes = Box.query.all()
		for b in boxes:
			item = DepositItemForm()
			item.boxNumber = b
			item.box = b.id
			item.amount = 0
			item.boxContent = b.content.name
			item.payOut = False
			item.ratio = b.content.ratio
			item.price = b.content.price
			item.amountLiter = 0
			item.amountEuro = "0.00"
			form.depositItems.append_entry(item)
		if(customer_id!=-1):
			customer = Customer.query.get_or_404(customer_id)
			form.customer.data = customer
			form.customerName = customer.name
	return render_template('addDeposit.html', form=form, fruits=FruitListForm(), emptyCustomer=(customer_id==-1))

@deposits.route("/viewDeposit/<int:deposit_id>", methods=['GET','POST'])
def viewDeposit(deposit_id):
	deposit = Deposit.query.get_or_404(deposit_id)
	return render_template('viewDeposit.html', deposit=deposit)

@deposits.route("/deleteDeposit/<int:deposit_id>", methods=['GET','POST'])
def deleteDeposit(deposit_id):
	deposit = Deposit.query.get_or_404(deposit_id)
	for depositItem in deposit.depositItems:
		db.session.delete(depositItem)
	db.session.delete(deposit)
	db.session.commit()
	flash('Gutschrift geloescht', 'success')
	return redirect(url_for("deposits.viewDeposits"))

flaskProg/templates/addCustomer.html
{% extends "main.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Neuer Kunde</legend>
				<div class="form-group">
					{{ form.name.label(class="form-control-label") }}
					{% if form.name.errors %}
						{{ form.name(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.name.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.name(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.street.label(class="form-control-label") }}
					{% if form.street.errors %}
						{{ form.street(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.street.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.street(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.zipcode.label(class="form-control-label") }}
					{% if form.zipcode.errors %}
						{{ form.zipcode(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.zipcode.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.zipcode(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.city.label(class="form-control-label") }}
					{% if form.city.errors %}
						{{ form.city(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.city.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.city(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.email.label(class="form-control-label") }}
					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.phone.label(class="form-control-label") }}
					{% if form.phone.errors %}
						{{ form.phone(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.phone.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.phone(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.mobile.label(class="form-control-label") }}
					{% if form.mobile.errors %}
						{{ form.mobile(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.mobile.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.mobile(class="form-control form-control-lg") }}
					{% endif %}
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form>
	</div>
{% endblock content %}

flaskProg/templates/addDeposit.html
{% extends "main.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Neue Gutschrift</legend>
				<div class="form-group">
					{{ form.date.label(class="form-control-label") }}
					{{ form.date(class="form-control form-control-sm") }}
				</div>
				<div class="form-group">
					Kunde
					{% if emptyCustomer %}
						{{ form.customer(class="form-control form-control-lg") }}
					{% else %}
						<br>
						{{ form.customerName }}
						{{ form.customer(class="invisible") }}
					{% endif %}
				</div>
				<div class="form-group">
					<table class="table table-striped table-sm">
						<tr><th>Kiste</th><th>Frucht</th><th>Menge (kg)</th><th>Auszahlen</th><th>Gutschrift</th><th>Auszahlung</th></tr>
						{% for l in form.depositItems %}
						{{ l.form.hidden_tag() }}
							<tr>
								<td>
									{{ l.form.box }}
									{{ l.form.boxNumber.data }}
								</td>
								<td>
									{{ l.form.boxContent.data }}
								</td>
								<td>
									{{ l.form.ratio }}
									{{ l.form.price }}
									{{ l.form.amount(class="form-control form-control-sm", onchange="deposit_calc_item(this);") }}
								</td>
								<td>
									{{ l.form.payOut(class="form-control form-control-sm", onclick="deposit_calc_item(this);") }}
								</td>
								<td>
									{{ l.form.amountLiter(class="form-control form-control-sm", readonly=true) }}
								</td>
								<td>
									{{ l.form.amountEuro(class="form-control form-control-sm", readonly=true) }}
								</td>
							</tr>
						{% endfor %}
						{% for l in form.emptyDepositItems %}
						{{ l.form.hidden_tag() }}
							<tr>
								<td>
									{{ l.form.boxNumber(class="form-control form-control-sm") }}
								</td>
								<td>
									{{ l.form.boxContent(class="form-control form-control-sm", onchange="deposit_calc_empty_item(this);") }}
								</td>
								<td>
									{{ l.form.amount(class="form-control form-control-sm", onchange="deposit_calc_empty_item(this);") }}
								</td>
								<td>
									{{ l.form.payOut(class="form-control form-control-sm", onclick="deposit_calc_empty_item(this);") }}
								</td>
								<td>
									{{ l.form.amountLiter(class="form-control form-control-sm", readonly=true) }}
								</td>
								<td>
									{{ l.form.amountEuro(class="form-control form-control-sm", readonly=true) }}
								</td>
							</tr>
						{% endfor %}
					</table>
					<table class="table table-striped table-sm">
						<tr>
							<th>Frucht</th>
							<th>Menge (kg)</th>
							<th>Menge (Liter)</th>
						</tr>
						{% for f in fruits.items %}
						<tr>
							<td>{{ f.form.name.data }}</td>
							<td>{{ f.form.amount(class="form-control form-control-sm", readonly=true) }}</td>
							<td>{{ f.form.total(class="form-control form-control-sm", readonly=true) }}</td>
						</tr>
						{% endfor %}
					</table>
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form>
		{% for f in fruits.items %}
			{{ f.form.id }}
			{{ f.form.name }}
			{{ f.form.price }}
			{{ f.form.ratio }}
		{% endfor %}
	</div>
{% endblock content %}

flaskProg/templates/addFruit.html
{% extends "main.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Neue Frucht</legend>
				<div class="form-group">
					{{ form.name.label(class="form-control-label") }}
					{{ form.name(class="form-control form-control-lg") }}
				</div>
				<div class="form-group">
					{{ form.ratio.label(class="form-control-label") }}
					{{ form.ratio(class="form-control form-control-lg") }}
				</div>
				<div class="form-group">
					{{ form.price.label(class="form-control-label") }}
					{{ form.price(class="form-control form-control-lg") }}
				</div>
				<div class="form-group">
					{{ form.pricePerLiter.label(class="form-control-label") }}
					{{ form.pricePerLiter(class="form-control form-control-lg") }}
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form>
	</div>
{% endblock content %}

flaskProg/templates/addPurchase.html
{% extends "main.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Neuer Verkauf</legend>
				<div class="form-group">
					{{ form.date.label(class="form-control-label") }}
					{{ form.date(class="form-control form-control-lg") }}
				</div>
				<div class="form-group">
					{{ form.customer.label(class="form-control-label") }}
					{% if emptyCustomer %}
						{{ form.customer(class="form-control form-control-lg") }}
					{% else %}
						<br>
						{{ form.customerName }}
						{{ form.customer(class="invisible") }}
					<h3>Guthaben</h3>
						<table class="table table-striped table-sm">
							<tr><th>Frucht</th><th>Guthaben</th></tr>
							{% for c in form.customerDeposits %}
							{{ c.form.hidden_tag() }}
							<tr>
								<td>{{ c.form.fruitName.data }}{{ c.form.fruit }}</td>
								<td>{{ c.form.amount(class="form-control form-control-sm", readonly=true) }}</td>
							</tr>
							{% endfor %}
						</table>
					{% endif %}
				</div>
				<div class="form-group">
					<h3>Artikel</h3>
					<table class="table table-striped table-sm">
						<tr><th>Artikel</th><th>Menge</th><th>Preis</th><th>Summe</th></tr>
						{% for l in form.purchaseItems %}
						{{ l.form.hidden_tag() }}
							<tr>
								<td>
									{{ l.form.articleName.data }}
									{{ l.form.article }}
								</td>
								<td>
									{{ l.form.amount(class="form-control form-control-sm", onchange="purchase_calc_item(this);") }}
								</td>
								<td>
									{{ l.form.price.data }}
								</td>
								<td>
									{{ l.form.total(class="form-control form-control-sm", readonly=true) }}
								</td>
							</tr>
						{% endfor %}
					</table>
					<h3>Ausgleich</h3>
					<table class="table table-striped table-sm">
						<tr>
							<th>Frucht</th>
							<th>Menge (Liter)</th>
							<th>Preis pro Liter</th>
							<th>Summe</th>
						</tr>
						{% for c in form.purchaseCompensations %}
						{{ c.form.hidden_tag() }}
						<tr>
							<td>{{ c.form.fruitName(class="form-control form-control-sm", readonly=true) }}{{ c.form.fruit }}</td>
							<td>{{ c.form.amount(class="form-control form-control-sm", readonly=true) }}</td>
							<td>{{ c.form.price(class="form-control form-control-sm", readonly=true) }}</td>
							<td>{{ c.form.total(class="form-control form-control-sm", readonly=true) }}</td>
						</tr>
						{% endfor %}
					</table>
					<h3>Gesamt</h3>
					<table class="table table-striped table-sm">
						<tr>
							<th>Frucht</th>
							<th>Menge (Liter)</th>
						</tr>
						{% for f in fruits.items %}
						<tr>
							<td>{{ f.form.name.data }}
								{{ f.form.id }}
								{{ f.form.name }}
								{{ f.form.price }}
								{{ f.form.ratio }}</td>
							<td>{{ f.form.total(class="form-control form-control-sm", readonly=true) }}</td>
						</tr>
						
						{% endfor %}
					</table>
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form>
	</div>
{% endblock content %}

flaskProg/templates/editArticle.html
{% extends "main.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Artikel bearbeiten</legend>
				<div class="form-group">
					{{ form.name.label(class="form-control-label") }}
					{% if form.name.errors %}
						{{ form.name(class="form-control form-control-lg") }}
						<div class="invalid-feedback">
							{% for error in form.name.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.name(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.desc.label(class="form-control-label") }}
					{% if form.desc.errors %}
						{{ form.desc(class="form-control form-control-lg") }}
						<div class="invalid-feedback">
							{% for error in form.desc.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.desc(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.fruit.label(class="form-control-label") }}
					{% if form.fruit.errors %}
						{{ form.fruit(class="form-control form-control-lg") }}
						<div class="invalid-feedback">
							{% for error in form.fruit.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.fruit(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.price.label(class="form-control-label") }}
					{% if form.price.errors %}
						{{ form.price(class="form-control form-control-lg") }}
						<div class="invalid-feedback">
							{% for error in form.price.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.price(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.amountLiter.label(class="form-control-label") }}
					{% if form.amountLiter.errors %}
						{{ form.amountLiter(class="form-control form-control-lg") }}
						<div class="invalid-feedback">
							{% for error in form.amountLiter.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.amountLiter(class="form-control form-control-lg") }}
					{% endif %}
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form>
	</div>
{% endblock content %}

flaskProg/templates/viewArticles.html
{% extends "main.html" %}
{% block content %}
	<h1>Artikel</h1>
	<table class="table table-striped table-sm">
		<tr><th>ID</th><th>Name</th><th>Frucht</th><th>Menge (Liter)</th><th>Preis</th><th></th><th></th></tr>
		{% for a in articles %}
			<tr><td>{{ a.id }}</td><td>{{ a.name }}</td><td>{{ a.fruit.name }}</td><td>{{ '{0:.2f}'.format(a.amountLiter) }} l</td><td>{{ '{0:.2f}'.format(a.price) }} Euro</td><td><a href="{{ url_for('articles.editArticle', article_id=a.id) }}">Bearbeiten</a></td><td><a href="{{ url_for('articles.deleteArticle', article_id=a.id) }}">Löschen</a></td></tr>
		{% endfor %}
		<tr><td></td><td><a href="{{ url_for('articles.addArticle') }}">neuer Artikel</a></td><td></td></tr>
	</table>
{% endblock content %}

flaskProg/templates/viewBoxes.html
{% extends "main.html" %}
{% block content %}
	<h1>Kisten</h1>
	<table class="table table-striped table-sm">
		<tr><th>ID</th><th>Nummer</th><th>Inhalt</th><th>Menge (kg)</th><th>Abgegeben am</th><th></th><th></th></tr>
		{% for b in boxes %}
			<tr><td>{{ b.id }}</td><td>{{ b.number }}</td><td>{{ b.content }}</td><td>{{ b.amount() }} kg</td><td>
			{% if(b.ended != None) %}
				{{ b.ended.strftime('%d.%m.%Y') }}
			{% endif %}
			</td><td><a href="{{ url_for('boxes.editBox', box_id=b.id) }}">Bearbeiten</a></td><td><a href="{{ url_for('boxes.deleteBox', box_id=b.id) }}">Löschen</a></td></tr>
		{% endfor %}
		<tr><td></td><td><a href="{{ url_for('boxes.addBox') }}">neue Kiste</a></td><td></td></tr>
	</table>
{% endblock content %}

flaskProg/templates/viewCustomers.html
{% extends "main.html" %}
{% block content %}
	<h1>Kunden</h1>
	<a href="{{ url_for('customers.addCustomer') }}">neuer Kunde</a>
	<table class="table table-striped table-sm">
		<tr><th>ID</th><th>Name</th><th>Straße<br>PLZ, Ort</th><th>
		{% for f in fruits %}
			{{ f.name }}<br>
		{% endfor %}</th><th>Bearbeiten</th><th>Aktion</th></tr>
		{% for c in customers %}
			<tr><td>{{ c.id }}</td><td>{{ c.name }}</td><td>{{ c.street }}<br>{{ c.zipcode }} {{ c.city }}</td><td>
			{% for f in fruits %}
				{% for a in c.amounts() %}
					{% if a[0] == f.name %}
						{% if a[2] != 0 %}
							{{ '{0:.1f}'.format(a[2]) }} l
						{% endif %}
					{% endif %}
				{% endfor %}
				<br>
			{% endfor %}
			</td>
			<td><a href="{{ url_for('customers.viewCustomer', customer_id=c.id) }}">Anzeigen</a>
				<br><a href="{{ url_for('customers.editCustomer', customer_id=c.id) }}">Bearbeiten</a>
				<br><a href="{{ url_for('customers.deleteCustomer', customer_id=c.id) }}">Löschen</a></td>
			<td><a href="{{ url_for('deposits.addDeposit', customer_id=c.id) }}">neue Gutschrift</a>
				<br><a href="{{ url_for('purchases.addPurchase', customer_id=c.id) }}">neuer Verkauf</a></td>
			<tr>
		{% endfor %}
	</table>
{% endblock content %}

flaskProg/templates/viewPurchases.html
{% extends "main.html" %}
{% block content %}
	<h1>Verkäufe</h1>
	<table class="table table-striped table-sm">
		<tr><th>ID</th><th>Datum</th><th>Kunde</th>
			{% for f in fruits %}
				<th>{{ f.name }} (Liter)</th>
			{% endfor %}
		<th>Summe</th><th></th><th></th></tr>
		{% for p in purchases %}
			<tr><td>{{ p.id }}</td><td>{{ p.date.strftime('%d.%m.%Y') }}</td><td>{{ p.customer }}</td>
			{% for f in fruits %}
				<td>
				{% for a in p.amounts() %}
					{% if a[0] == f.name %}
						{{ '{0:.1f}'.format(a[1]) }} l
					{% endif %}
				{% endfor %}
				</td>
			{% endfor %}
			<td>{{ '{0:.2f}'.format(p.total()) }} Euro</td><td><a href="{{ url_for('purchases.viewPurchase', purchase_id=p.id) }}">Anzeigen</a></td><td><a href="{{ url_for('purchases.deletePurchase', purchase_id=p.id) }}">Löschen</a></td></tr>
		{% endfor %}
		<tr><td></td><td><a href="{{ url_for('purchases.addPurchase') }}">neuer Verkauf</a></td><td></td></tr>
	</table>
{% endblock content %}